version: '3'
services:
  iris: 
    build: .
    ports:
      - 52773
    command: 
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
    volumes:
      - ./tests:/home/irisowner/isc-tar/tests
