name: push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build and Test
        run: make build
      - name: Release
        run: make release
      - name: Upload Release Asset
        if: github.event_name == 'release'
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/zUtils.FileBinaryTar.xml
          asset_name: zUtils.FileBinaryTar.xml
          asset_content_type: text/xml
