name: push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Test
        run: make build
      - name: Release
        run: make release
